openstax/enki

- Dockerfile
- Dockerfile.common
- cli.sh
- test.sh
- add vim & nano to the container
- rebuild `Dockerfile` every time `cli.sh` runs
- copy the `/dockerfiles/build/*` scripts
- (...maybe more?)
> Add debugging features

- Dockerfile
- Dockerfile.common
- dockerfiles/steps/archive-gdocify.bash
- dockerfiles/steps/archive-link-rex.bash
- dockerfiles/steps/git-link-rex.bash
> fix tasks that use the ABL for book slugs

- dockerfiles/steps/git-bake.bash
- show full baking error stack trace
> :art: Kaizen updates for diagnosing baking problems

- build-concourse/env/corgi-local.json
- build-concourse/env/corgi-production.json
- build-concourse/env/corgi-staging.json
- build-concourse/env/gdocs-local.json
- build-concourse/env/gdocs-production.json
- build-concourse/env/webhosting-local.json
- build-concourse/env/webhosting-production.json
- cli.env
> Rename ABL branch

- dockerfiles/steps/git-fetch.bash
> update to yappy.yakutsk

- .gitmodules
Since we install princexml in our Dockerfile
> :fire: remove princexml submodule

- build-concourse/README.md
- build-concourse/docker-compose.yml
- dockerfiles/docker-entrypoint.sh
- dockerfiles/steps/git-bake.bash
> Use repo style when "default" is specified

- dockerfiles/docker-entrypoint.sh
This change should allow webhosting pipeline to advance to the point where it will check the books.xml for the style.
> Fix read style for webhosting pipeline

- bakery-src/scripts/checksum_resource.py
- bakery-src/scripts/copy_resources_s3.py
- bakery-src/scripts/requirements.txt
- bakery-src/scripts/utils.py
- bakery-src/tests/data/fffe62254ef635871589a848b65db441318171eb.json
- bakery-src/tests/test_bakery_scripts.py
Will be used by Rex prerendering at some point
> Set image size metadata when uploading images to S3

- dockerfiles/steps/git-fetch-metadata.bash
This was breaking the GitHub Actions
> :bug: do not assume curdir contains resources/

- bakery-src/scripts/fetch_map_resources.py
- bakery-src/tests/test_bakery_scripts.py
separate two loops and save width and height also in metadata dictionary.
> fix image calculation bug

- test/test-step-01.bash
- test/test-step-08.bash
- test/test-step-11.bash
It was using a CNX book (virology) which was causing the tests to fail
> Use different book so tests pass

- build-concourse/build-corgi.ts
- build-concourse/step-definitions.ts
- dockerfiles/steps/git-docx-meta.bash
- dockerfiles/steps/git-epub.bash
I also added a fix for `.epub` output paths being relative when built in concourse.
> Various fixes for epub

- Dockerfile
- Dockerfile.common
It looks like this may be a simple upgrade 😌
> 2027 - Update node to version 18

- bakery-src/scripts/utils.py
refs https://github.com/openstax/ce/issues/2026
> :bug: fix data-toc-type to be snake_case

- bakery-js/src/model/base-toc.tsx
- codecov.yaml
These are a few changes I encountered
> misc small changes

- README.md
- bakery-src/tests/test_cli.js
- build-concourse/README.md
- build-concourse/env/corgi-production.json
- build-concourse/env/corgi-staging.json
- build-concourse/env/gdocs-production.json
- build-concourse/env/webhosting-production.json
- build-concourse/env/webhosting-sandbox.json
- build-concourse/util.ts
since we do not need credentials to download images from DockerHub anymore. Thanks @bkblodget !
> :fire: remove Docker Credentials

- .github/workflows/test.yml
Some started giving warnings, others are a bit overdue
> upgrade some versions of packages

- cross-lib/README.md
- cross-lib/run_enki_on_all.sh
[#5104](https://github.com/openstax/cnx-recipes/issues/5104)
Adds --data-dir option and documentation to run-enki-on-all.sh
> Add --data-dir option and documentation to run-enki-on-all.sh

- bakery-src/scripts/package-lock.json
- dockerfiles/steps/step-pdf.bash
- dockerfiles/steps/step-prebake.bash
- test/test-step-02.bash
- test/test-step-08.bash
Depends on openstax/mathify#76
Fixes openstax/ce#2038
If an assembled file contains `data-math=`, mathify it.
One potential problem is that mathify inserts styles into the head each time it is run. I think many of these styles are unique; however, it might bloat the document if there are duplicated styles.
> 2038 - exercise math fix

- README.md
- build-concourse/graphs/README.md
- build-concourse/step-definitions.ts
- dockerfiles/steps/step-bake.bash
- step-config.json
Supports openstax/cnx-recipes#4917
In conjunction with openstax/cookbook#230
> pass in resources when bake is called

- cross-lib/README.md
- cross-lib/run_enki_on_all.sh
- cross-lib/update_books.rb
> change cross-lib builder to build by repo not slug

- corgi-concourse-resource/corgi_concourse_resource/out.py
step-upload is printing binary data which caused an encoding error.
> Replace binary data in the log when posting to CORGI

- nebuchadnezzar/nebu/formatters.py
- nebuchadnezzar/requirements/main.txt
It's on bootcamp/hotdog!
[Backoff](https://pypi.org/project/backoff/)
> Neb add expo backoff in exercise fetching

- .github/workflows/test.yml
- bakery-src/scripts/copy_resources_s3.py
- bakery-src/tests/test_bakery_scripts.py
fixes openstax/ce#2075
`map_async` is an async generator that takes a function, an iterable containing arguments to pass, a worker count, and an optional qsize. For each argument, it yields a (result, error) tuple. This improves error handling because it yields the original error which we can then raise again. It also encapsulates the details of the concurrency pattern into one function.
It uses what I like to call FWATAP (Feeder Worker Aggregator Task-Based Asynchronous Pattern): a concurrency pattern inspired by Go channels and goroutines.
This library is required by pygit2. It is also being installed in the Enki Dockerfile. We did not need to install it for python 3.8, but we do for python 3.10.
Try it on 🌭 (bootcamp)
> S3 upload asyncio

- bakery-js/README.md
- bakery-js/src/epub/__snapshots__/toc.test.ts.snap
- bakery-js/src/epub/toc.test.ts
- bakery-js/src/epub/toc.tsx
- bakery-js/src/index.ts
fixes https://github.com/openstax/ce/issues/2074
> Add epub3 cover

- bakery-js/src/epub/__snapshots__/toc.test.ts.snap
- bakery-js/src/epub/toc.test.ts
- bakery-js/src/epub/toc.tsx
- bakery-js/src/index.ts
- bakery-js/src/model/file.ts
- dockerfiles/steps/step-bake.bash
- dockerfiles/steps/step-epub.bash
- dockerfiles/steps/step-pdf.bash
Refs https://github.com/openstax/ce/issues/2082
> fixes the ToC so Chapter titles are links

- Dockerfile
- bakery-js/src/index.ts
- dockerfiles/steps/step-bake.bash
- dockerfiles/steps/step-prebake.bash
Trying out [Tyler's suggestion](https://openstax.slack.com/archives/C0LA54Q5C/p1692897226919599?thread_ts=1692895953.852499&cid=C0LA54Q5C) to re-enable webfonts to be used?
> Re-enable web fonts?

- nebuchadnezzar/nebu/xsl/cnxml-to-html5.xsl
Issue: https://github.com/openstax/cnx-recipes/issues/5270
> add class to footnote link

- Dockerfile
- cli.env
- dockerfiles/10-fix-perms.sh
- dockerfiles/docker-entrypoint-with-kcov.sh
- dockerfiles/docker-entrypoint.sh
- enki
- test/test-step-02.bash
- test/test-step-03.bash
- test/test-step-05.bash
- test/test-step-11.bash
> Try to match concourse directory structure

- build-concourse/graphs/README.md
regenerated these in #302, then changed things, didn't regenerate again 🙊 they're fixed now
> fix documentation for docx

- dockerfiles/docker-entrypoint.sh
- dockerfiles/steps/step-prebake.bash
Check that book slugs supplied on command line, or by CORGI, are in the book repository at the start of prebake.
> Check book slug arg is in book repository during prebake

- nebuchadnezzar/nebu/parse.py
- nebuchadnezzar/nebu/tests/test_parse.py
part of openstax/ce#1528
depends on #371 
Try to use cnxml title first. If that does not exist, use mdml title (ideally only for collections). If that does not exist, raise IndexError.
> Assemble - 1528 prioritize cnxml title

- build-concourse/build-webhosting.ts
- build-concourse/env/webhosting-local.json
- build-concourse/env/webhosting-production.json
- build-concourse/env/webhosting-sandbox.json
- build-concourse/script/check_feed.sh
- build-concourse/step-definitions.ts
- build-concourse/util.ts
- dockerfiles/steps/git-dequeue-book.bash
- dockerfiles/steps/git-report-book-complete.bash
part of openstax/ce#2263
STATE_PREFIX must be the same in check-feed and git-report-book-complete QUEUE_SUFFIX must be the same in check-feed and git-dequeue-book
Using variables helps ensure these requirements are met
> 2263 - Add STATE_PREFIX and QUEUE_SUFFIX to webhosting env

- dockerfiles/steps/step-jsonify.bash
- dockerfiles/steps/step-upload-book.bash
https://openstax.atlassian.net/browse/CORE-868
> Core 868 web duplicate slug check
