- README.md
- google-docs.md
- test/test-step-04.bash
The newer sociology recipe will break these tests because it assumes `(2e)` is in the title. This unblocks upgrading the recipes submodule
> use sociology2e for testing since recipes break

- build-concourse/step-definitions.ts
- step-config.json
Resources were empty in concourse because it was not specified as an input to the git-pdf step.
The broken [git-pdfify step](https://concourse-v7.openstax.org/teams/CE/pipelines/corgi-staging/jobs/PDF%20(git)/builds/59#L6112c8a9:179):
```
prince: loading image: resources/56c7b5a4cbf3329a608284ec89fae72c9f19e664
prince: resources/56c7b5a4cbf3329a608284ec89fae72c9f19e664: warning: can't open input file: No such file or directory
prince: loading image: resources/afc1495a68d2b9bf2df6068d2a0e42dd5c9ca6b1
prince: resources/afc1495a68d2b9bf2df6068d2a0e42dd5c9ca6b1: warning: can't open input file: No such file or directory
prince: loading image: resources/fe5751e479a8db23cd6f731eda8645d9ae88e4de
prince: resources/fe5751e479a8db23cd6f731eda8645d9ae88e4de: warning: can't open input file: No such …
```
> Add resources as input directory to PDF

- dockerfiles/steps/git-fetch.bash
Folks were seeing a cryptic "Missing username" when git was cloning a private repo
> Warn when the GH_SECRET_CREDS env token is missing

- build-concourse/env/corgi-production.json
Old CORGI prod generated URLs with `/apps/archive-preview/` and richb-press incorrectly pointed to `/apps/archive/`.
This fixes that bug
> BUG: Rename corgi-prod to use archive-preview

- Dockerfile
- Dockerfile.common
- README.md
- build-concourse/README.md
- build-concourse/env/corgi-local.json
- build-concourse/env/corgi-production.json
- build-concourse/env/corgi-staging.json
- build-concourse/env/gdocs-local.json
- build-concourse/env/gdocs-production.json
- build-concourse/env/webhosting-local.json
- build-concourse/env/webhosting-production.json
- build-concourse/env/webhosting-sandbox.json
- google-docs.md
There were 2 problems encountered:
1. The docker registry image is now `richb-press` instead of book-pipeline so this replaces all references
2. The AWS credentials were flipped for the sandbox webhosting pipeline
> Fix sandbox webhosting

- build-concourse/env/corgi-local.json
- build-concourse/step-definitions.ts
- cli.env
- cli.sh
- dockerfiles/steps/git-upload-book.bash
- step-config.json
We were only uploading book xhtml/json files (using `aws s3 cp --recursive`) and resource files (using `copy-resources-s3`).
This uploads resources/ subdirectories (like interactives)
And s3 autodetects the mimetype (even for TTF font files)
> upload subdirectories inside /resources/

- dockerfiles/steps/git-fetch.bash
- test/test-step-03.bash
This adds support for building books off of a git branch. Since we cannot clone just a commit we try to find the commit with these progressively-larger operations:
1. perform a shallow clone using the 50 most recent commits on the main branch
2. pull the 50 most recent commits on all branches
3. perform a deep clone
> build book from a git branch

- dockerfiles/steps/archive-bake-metadata.bash
- dockerfiles/steps/archive-fetch-metadata.bash
Baking archive books fails with the new ABL schema change to support git books. 
This change ignores the git entries in the ABL so the intermediate JSON contains pairs of uuid/slug instead of what it does now:
```
[
null,
null,
{uuid: ..., slug: ...},
{uuid: ..., slug: ...},
{uuid: ..., slug: ...},
]
```
> :bug: fix ABL schema change

- .env.example
- README.md
- cli.sh
This hopefully addresses 3 annoyances:
1. it would be useful for style devs to mount a custom recipes directory instead of using the version in this repo submodule.
2. cloning private repos requires setting a `GH_SECRET_CREDS` environment variable which is annoying to specify all the time or annoying to put in a bash profile
2. Remembering all the environment variables is annoying, especially if you just want to rebake a book without re-cloning it all the time
You can put all the environment variables into a `.env` (aka "dotenv") file in the current directory and the script will read them. This is useful for storing the GH_SECRET_CREDS, TRACE_ON, START_AT_STEP, and other environment variables.
You can set a `RECIPES_ROOT` environment variable to point to your local in-development recipes …
> add dotenv file and ability to mount recipes dir

- cli.env
- cli.sh
- dockerfiles/docker-entrypoint.sh
- test/test-step-06.bash
#49 fixed a bug that occurs in concourse but not locally. Locally, directories always exist but in concourse, only directories that are specified in the task as input/output are available. This PR reproduces those semantics but locally. That way the error fixed in #49 will not occur again (because it will be caught locally)
To handle the 2 cases above, we create an `_attic/` directory and perform a little housekeeping before and after each step runs:
1. **Before:** copy all [input](https://concourse-ci.org/tutorial-inputs-outputs.html#what-are-inputs-and-outputs) directories from the attic into the workspace
2. **After:** move all [output](https://concourse-ci.org/tutorial-inputs-outputs.html#what-are-inputs-and-outputs) directories from the workspace into the the attic
3. **After:** …
> Simulate Concourse directory semantics locally

- dockerfiles/steps/git-pdfify-meta.bash
- test/test-step-02.bash
- test/test-step-03.bash
A branch with `#` resulted in a broken URL because the `#` was in the filename and browsers ignore `#` and everything following it when making a request to a webserver.
[Slack Context](https://openstax.slack.com/archives/C0LA54Q5C/p1640017885387700?thread_ts=1639770737.364100&cid=C0LA54Q5C)
> :bug: branches with '#' in the name

- .gitmodules
> switch submodules to use their `main` branches

- test/test-step-09.bash
Just a small addition to warn you if you are running tests locally and shellcheck is not installed. It can be frustrating to discover liniting problems after creating a pull request.
> Update test-step-09: warn when shellcheck absent

- build-concourse/env/webhosting-sandbox.json
We can switch it to another branch name in the future if we need to test ABL-specific changes (like a schema upgrade)
> switch sandbox back to using the main ABL branch

- cli.env
refs [1830](https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/ce/1830)
Updating the `ABL_FILE_URL` in cli.env should not impact CORGI or Webhosting since they have their own definition for that variable that is inserted into the YAML files when you run their build scripts. It should only impact the cli. Granted, we should probably remove archive tests entirely at some point.
This change does have larger implications in that the static commit will be used for any archive jobs executed on the command line. Archive jobs through CORGI, however, will still use the main branch of the ABL. If this becomes a problem for local development, the environment variable can be updated locally.
> Change ABL_FILE_URL in cli.env to specific commit

- .github/workflows/test.yml
- bakery-src/scripts/gdocify_book.py
- bakery-src/scripts/setup.py
- bakery-src/tests/test_bakery_scripts.py
- test/test-step-10.bash
* A valid git book
* You build the repository into a doc using a script like this one
```sh
repo="osbooks-calculus-bundle"
slug="calculus-volume-1"
book_dir="./data/$(basename "$repo")"
./enki --command all-git-gdoc  --data-dir "$book_dir" --repo "$repo" --book-slug "$slug" --ref main --style default
```
* You will find the finished docs in `$book_dir/_attic/IO_DOCX`
* The build should succeed and all the correct content should exist in the finished docs.
* Everything should work the same as before except the git-gdocify step will, hopefully, complete in less time
---
Add an async queue that allows converting multiple images at a time. The worker count, 20, may need to be tweaked depending on the environment. In my testing on Gitpod, having 20 workers converting images concurrently …
> 1914 gdocify multitasking

- bakery-src/scripts/gdocify_book.py
- bakery-src/tests/test_bakery_scripts.py
- dockerfiles/steps/git-gdocify.bash
* Have the enki repository cloned from GitHub
* Be in the root directory of enki
* If you want to build with a private repo, you will need to [create and set a GitHub access token](https://github.com/openstax/enki#set-a-github-token)
- A valid bundled book repo (osbooks-...-bundle)
- Building to docx (i.e. all-git-gdocify)
- Links within the docx files that go to openstax.org should work for each book slug
- Note: When you see more than one of the same `chapter-section` pair, that is a good indication that those documents are from different book slugs (example:  9-1-title-here.docx vs. 9-1-different-title.docx would be from different book slugs)
Update docx links for all modules using their respective book slug/uuid.
Remove use of *.toc.json file since we were only using the uuid from it …
> Update docx links independently for each book slug

- dockerfiles/steps/git-convert-docx.bash
- dockerfiles/steps/git-gdocify.bash
This is meant to preserve page slugs that share the same name between
book slugs (i.e. 1-summary in volume 1 vs 1-summary in volume-2).
Prior to this change, page slugs with the same name were being
overwritten in the process of building bundles.
Another option would be to add the book slug to the beginning of each
file name ({book_slug}-{page_slug}.docx). I decided to use directories
because it makes it easier to inspect the output of the build when
needed.
The other option might make more sense when uploading the files to
an external service. If that happens, we can flatten the directories
and add the book slug to the name of each docx file as it is uploaded.
> Use book slug as directory during docx conversion

- bakery-src/scripts/gdocify_book.py
- bakery-src/tests/test_bakery_scripts.py
Hopefully this will fix the random mogrify errors we were seeing. I
believe the problem was that images were being queued for conversion
multiple times. This may have caused multiple instances of mogrify to
modify the same file in-place at the same time.
Also add an argument for process count. If process count is not given,
default to cpu_count if possible, else 4.
> 1914 Ensure images are only queued for conversion one time.

- bakery-src/scripts/gdocify_book.py
- bakery-src/tests/test_bakery_scripts.py
* osbooks-prealgebra-bundle
* Building the book to docx with CORGI
* The build passes
* The solutions in 4-3-multiply-and-divide-mixed-numbers-and-complex-fractions.docx look similar to what is [online](https://openstax.org/books/prealgebra-2e/pages/4-3-multiply-and-divide-mixed-numbers-and-complex-fractions#fs-id1409316). Specifically, there should still be slashes over numbers in numerators and denominators to show that the factors "cancel out".
---
The slash character used to cross out a number, \u0338, seems to cause translation errors when it is inside mi or mn tags; however, it is fine inside mtext. This PR adds a patch to gdocify_book.py that converts mi and mn tags to mtext if they contain \u0338. The math should still look very similar to what is online.
> 1933 Change mn/mi containing u0338 to mtext for docx

- bakery-src/scripts/fetch_map_resources.py
- bakery-src/tests/test_bakery_scripts.py
fixes key error web pipeline. Pipeline `all-git-web` calculates checksums of resources in `fetch_map_resources.py`
Only old pipeline `all-archive-web` uses the `checksum_resource.py` file nowadays.
> calculate width and height on resources

- dockerfiles/docker-entrypoint.sh
- dockerfiles/steps/git-assemble-epub.bash
- dockerfiles/steps/git-assemble.bash
- dockerfiles/steps/git-fetch-metadata.bash
- dockerfiles/steps/git-fetch.bash
* Make sure git-fetch and git-fetch-metadata use the same logic to determine which git ref to use
* Remove zombie code that caused only one book to be assembled while building a bundle.
> Various fixes related to parse_book_dir

- dockerfiles/steps/git-fetch.bash
This came up when deploying a webhosting pipeline. Validating unbound variables in bash was added as part of the EPUB PR
> :bug: fix unbound variable when running in a webhosting pipeline

- Dockerfile
- Dockerfile.common
- dockerfiles/fix-perms
- enki
This forces non-amd64 architectures (like the Apple M1) to run in emulation mode.
This is a stop-gap solution while we upgrade all the dependencies to enable an arm64 image.
> Get M1 Mac to work

- bakery-src/scripts/html_parser.py
This fix should solve the following bug that was caused by migrating `cnxepub.html_parser.py` into `enki`
```
File "/workspace/enki/venv/lib/python3.8/site-packages/bakery_scripts/html_parser.py", line 226, in fix_links
Logger.error('Bad href: {}'.format(
TypeError: error() missing 1 required positional argument: 'msg'
```
> Fix for the bad href error

- Dockerfile
- Dockerfile.common
Related to openstax/ce-images#15
I want to pin this image just in case we are using poetry in a way that is no longer supported in the newest version. From what I have seen and read, it should be safe to update; however, I would rather the update be done on our terms than automatically.
> Pin python3-poetry to 20220614.214642

- .github/workflows/test.yml
Ghostscript was not being found. It looks like there is a newer version that we can use instead.
> Quick fix for tests

- .gitpod.yml
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- bakery-js/bin/bakery-helper
They used to require the host to run `npm install && npm build` so VSCode could map to the source TS/TSX files.
Instead, this runs ts-node which transpiles the TS files in-memory which implicitly causes the node debugger to send the path to the TS files to the host (VSCode) rather than the path to the JS file which only exists inside the container
> simplify bakery-js breakpoints

- dockerfiles/docker-entrypoint.sh
- dockerfiles/steps/step-docx.bash
When the debugger attached to pm2, it would get disconnected unexpectedly.
I made the script wait for a debugger to attach because the python that depends on the json rpc would fail if you did not attach the debugger in time.
[/proc/net/tcp docs](https://www.kernel.org/doc/html/v5.8/networking/proc_net_tcp.html)
> Use node for json rpc debugging instead of pm2

- Dockerfile
Unfortunately, I did not catch this in the last PR. On the bright side, it is a simple fix and we found it prior to the next release 🎉.
> Copy aws cli into final build stage

- bakery-src/scripts/copy_resources_s3.py
- bakery-src/tests/test_bakery_scripts.py
fixes openstax/ce#2078
(Yes, different commits, but both commits had the same number of images)
---
This started as an exploration, but the results were so dramatic that I thought I should make a PR. I guess creating a new session for each upload was taking quite a bit of time. The connection errors might have also been caused by creating one connection per resource.
Since we cannot safely share sessions/clients between threads, I made each thread process an array of inputs.
What happens when there is an error? While I was poking around at this, I ran into a key error because I forgot that metadata defaulted to `None` in the past. Since the worker surfaces any exceptions immediately after they occur, the entire upload process fails as expected:
> S3 upload in chunks

- Dockerfile
- test/test-step-10.bash
More details:
* https://github.com/aws/aws-cli/issues/8036#issuecomment-1638544754
* https://github.com/yaml/pyyaml/issues/601
PyYAML Version taken from [awscli](https://github.com/aws/aws-cli/blob/dbbf1ce01acec0116710968bbe5a96680e791c1b/setup.py#L30)
> Add workaround for failing pyyaml builds

- Dockerfile
- bakery-src/scripts/requirements.txt
The PyYAML pin was added as a workaround to a cython issue that affected versions (5.3.1, 6.0.0] of PyYAML. This newer version of the aws cli supports version 6.0.1 of PyYAML. Consequently, this update makes the PyYAML workaround unnecessary.
I looked into upgrading to v2 of the aws cli as well; however, while you can upgrade and use that version (see v2 branch of the repo), it is still under development.
> Update awscli to 1.29.25

- bakery-js/src/epub/page.test.ts
- bakery-js/src/epub/page.tsx
`<a id="1">..</a>` tags without `href` are still valid HTML. They are like real "anchors" or like "bookmarks" to be jumped to by id.
> ignore all anchor tags without href, they are still valid html

- Dockerfile
There was a deprecation warning with a timeout.
[Here](https://github.com/nodesource/distributions#nodejs) you can find more details about this change.
> Update process for installing node

- nebuchadnezzar/nebu/cli/assemble.py
- nebuchadnezzar/nebu/models/book_container.py
- nebuchadnezzar/nebu/tests/test_xml_utils.py
* This change deployed to CORGI
* [osbooks-mikroekonomia](https://github.com/openstax/osbooks-mikroekonomia) is built in CORGI
* [osbooks-psychologia](https://github.com/openstax/osbooks-psychologia) is built in CORGI
* The job completes successfully
---
Quick fix for the two books that failed in the Friday webhost pipeline. They failed because their books.xml file declaration includes an encoding. I also added a test for a variety of encoding scenarios.
> Books xml encoding

- dockerfiles/steps/step-pdf.bash
- dockerfiles/steps/step-prebake.bash
- test/test-step-02.bash
fixes openstax/ce#2139
Some notes:
- `code` tags are converted to `pre` tags in the xslt (see integration test)
> 2139 prebake code highlighting

- bakery-src/scripts/fetch_map_resources.py
- bakery-src/tests/test_bakery_scripts.py
- dockerfiles/steps/step-prebake.bash
- test/test-step-03.bash
fixes openstax/ce#2148
You may be wondering: why not just move all subdirectories of resources path into a versioned directory? I was a little concerned that, that could break some resource paths. Since we explicitly rewrite iframe resource paths, I thought it would be safer to limit the scope of this change to those. Especially since this is only meant to fix a caching issue. 
Example output with real paths removed (from building a book on hotdog):
`rewriting iframe source from ../../media/interactive/... to ../resources/e5ff71c/interactive/...`
> 2148 versioned interactives

- bakery-js/src/index.ts
- dockerfiles/steps/bake-util.bash
- dockerfiles/steps/step-pdf.bash
- test/test-step-12.bash
fixes openstax/ce#2186
Create and use one css file per book slug.
There was a style/recipe name sent to cookbook and a style file copied from ce-styles into later build stages. There was a loop that read the style for each book slug. The loop was continuously overwriting the style file `the-style-pdf.css` which was being used in subsequent steps.
That means that while the correct style/recipe was being used to cookbook, the wrong css file was sometimes being copied to later steps (for bundles where there was more than one style).
This change makes it so bake-util.bash will create one css file per book slug.
- pdf works because prince/mathjax determine which css file to load based on the style in the head (which is inserted by the `sed` command)
- epub works because it reads the css file …
> 2186 use one css file per book when building epub and pdf

- dockerfiles/steps/step-fetch.bash
fixes openstax/ce#2168
More information about what this command does can be found in git/builtin/submodule--helper.c
Short version of what it does:
1. Clone submodule with depth 1
2. Runs `git fetch` if tip is unreachable
3. Runs `git fetch <default-remote> <commit-sha>` if tip is still unreachable
4. Fails if tip is still unreachable
5. Runs `git checkout <commit-sha>` in the submodule
> Initialize submodules during step-fetch

- .github/problem-matcher.json
- .github/workflows/test.yml
- dockerfiles/docker-entrypoint-with-kcov.sh
- test/test-step-08.bash
fixes openstax/ce#2213
Use jq to generate coverage warnings that are subsequently recognized by a Github problem matcher and annotated in the PR source code/files changed view.
Example:
> 2213 ci no codecov

- bakery-src/scripts/html_parser.py
fixes openstax/ce#2234
part of openstax/ce#1528 ("Verify cnx-epub does not rely on metadata title elements for the modules during the disassemble step")
openstax/ce#1528 would see md:title replaced by c:title for modules. Disassemble used titles as a key for generating ids. This PR seeks to clarify and ensure that only titles from collxml md:title tags are used to generate ids.
> Disassemble - only use titles to compute id if the element is a chapter or unit

- bakery-src/scripts/check_feed.py
- bakery-src/tests/test_bakery_scripts.py
- build-concourse/build-corgi.ts
- build-concourse/build-webhosting.ts
- build-concourse/env/webhosting-sandbox.json
- build-concourse/util.ts
The webhosting pipeline builds all books in a repository; therefore, we only need to queue each version of a repository once.
> check_feed: Filter abl_json down to unique entries based on repo and commit sha

- dockerfiles/steps/step-epub.bash
For future reference, here are some examples of where this is a problem:
```html
<h3 data-type="title">...<pre data-type="code" class="python inline-code" data-lang="python">...</pre></h3>
<span class="os-title" data-type="title">...<pre data-type="code" class="python inline-code" data-lang="python">...</pre></span>
<span class="os-caption" data-type="title">...<pre data-type="code" class="python inline-code" data-lang="python">...</pre></span>
```
The python book (and likely data-science as well) have code in titles and captions. This code is converted into `pre` during `step-assemble`. Since the title element is a span (inline), it is not supposed to contain a block-level element -> validation error.
In summary:
* `span` tags cannot contain block-level `pre` tags
* `h3` tags should only …
> Ignore errors related to pre tags in epub validation

- bakery-js/src/index.ts
- dockerfiles/docker-entrypoint.sh
- dockerfiles/steps/step-prebake.bash
- dockerfiles/steps/step-upload-book.bash
part of openstax/ce#2073
Pipe a list of files to the node process so that we do not need to start a new instance of node for each file annotated
Enable annotation if IO_BOOK/job_id exists (true for local and corgi)
See changes to the `if` in step-upload-book.bash for additional background on the reasoning behind using IO_BOOK/job_id.
> Annotate xml files faster; enable annotation on corgi

- bakery-js/src/index.ts
- bakery-src/scripts/pptify_book.py
- bakery-src/tests/test_bakery_scripts.py
- dockerfiles/steps/bake-util.bash
- dockerfiles/steps/step-bake.bash
- dockerfiles/steps/step-pdf.bash
- dockerfiles/steps/step-pptx.bash
- dockerfiles/steps/step-prebake.bash
part of openstax/ce#2083
- Copy downloaded fonts where required (pdf, epub, and pptx)
- Do not upload fonts to S3 (this may have created a problem last time due to the replicator? Also, there's not reason to do it since the fonts are not used in the webview style.)
- Remove some unnecessary parts of `xhtml_to_img` in `pptify_book` (The `enable-local-file-access` option allows general file access and you do not need to specify specific directories in this case.)
- Set log level to `warn` for imgkit in pptify_book (warn is the minimum level that logs missing files)
- Update tests for `pptify_book` to reflect changes.
**Note**: This should not be merged before the ce-styles [PR](https://github.com/openstax/ce-styles/pull/549) that enables local fonts due to the changes in …
> Epub font download activate rebased

- nebuchadnezzar/nebu/tests/snapshots/test_converters/test_diffs/footnote.xhtml
- nebuchadnezzar/nebu/xsl/cnxml-to-html5.xsl
https://openstax.atlassian.net/browse/CORE-740
1. Footnote asides are added outside of parent elements to the nearest footnote dumpsite
1. Note titles were not a footnote dumpsite
1. Footnotes from note titles were added to the next nearest dumpsite: note body
1. There is a template for para that has higher priority than the note template
1. ~Since these both dumped to note body and para had higher priority, the para footnote was added to the note body before the title footnote. This caused incorrect ordering.~ Correction: Since para is a footnote dumpsite, the aside for the footnote para was added immediately after the para, which is why it came before the aside for the note title para and why the numbering was reversed.
Solution: make note titles a footnote dumpsite and then dump title …
> Assemble: Make note title a footnote dumpsite

- .github/workflows/test.yml
- bakery-js/src/index.ts
- bakery-src/scripts/check_feed.py
- bakery-src/tests/test_bakery_scripts.py
- build-concourse/build-webhosting-local.ts
- build-concourse/build-webhosting.ts
- build-concourse/env/webhosting-production.json
- build-concourse/env/webhosting-sandbox.json
- build-concourse/package.json
- build-concourse/script/check_feed.sh
- build-concourse/step-definitions.ts
- build-concourse/util.ts
- cli.env
- step-config.json
- test/test-step-10.bash
https://openstax.atlassian.net/browse/CORE-1006
I also added support for using `chat.postMessage`. I figured it was not much extra work and might be useful in the future.
Sorry about the extra stuff. These were some small changes I had in my working tree that were going to be needed eventually, but didn't really fit into other stuff.
* The PyYAML version thing was a temporary workaround that was no longer needed.
* The step config is something that should have been committed with the change that caused it to change.
* The xml annotation thing was a problem that came up during algebra-1 development. Since it's only annotating, I don't think the entire build should fail if it runs into problems. Plus, there is better error handling in other parts of the pipeline.
> CORE-1006 - WebHosting Slack Notifications
